"""empty message

Revision ID: 177979a1ffd0
Revises: 
Create Date: 2023-11-24 20:45:46.284401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '177979a1ffd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('source_folder', sa.String(), nullable=False),
    sa.Column('destination_folder', sa.String(), nullable=False),
    sa.Column('palate_configuration', sa.String(), nullable=False),
    sa.Column('base_height', sa.Float(), nullable=False),
    sa.Column('project_status', sa.String(), nullable=False),
    sa.Column('change_log', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('destination_folder'),
    sa.UniqueConstraint('project_name'),
    sa.UniqueConstraint('source_folder')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.Column('last_login_datetime', sa.DateTime(), nullable=True),
    sa.Column('user_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('task',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('project', sa.Uuid(), nullable=True),
    sa.Column('task_status', sa.String(), nullable=False),
    sa.Column('preprocess_path', sa.String(), nullable=False),
    sa.Column('destination_path', sa.String(), nullable=False),
    sa.Column('error_log', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('task_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('users')
    op.drop_table('project')
    # ### end Alembic commands ###
